"""Database engines and session factories.

Public surface:
    engine                — async engine (asyncpg / aiosqlite)
    AsyncSessionLocal     — async session factory
    get_db()              — FastAPI dependency yielding AsyncSession
    session_scope()       — async context manager yielding AsyncSession
    sync_engine           — async engine's internal sync wrapper (no extra pool)
    SyncSessionLocal      — sync session factory (scripts + tests only)
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager, contextmanager
from typing import Iterator

from sqlalchemy.engine.url import make_url
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from sqlalchemy.orm import Session, sessionmaker

from app.config import settings
from v2.modules.platform_infra.logging.logger import get_logger

logger = get_logger(__name__)

# ── Engine wiring ─────────────────────────────────────────────────────────────
# Tier E madde 30: prefer the pooled (pgbouncer) URL for the app engine when
# set; DATABASE_URL itself (used by Alembic/scripts) always stays direct.
_url = make_url(settings.DATABASE_URL_POOLED or settings.DATABASE_URL)

# Force asyncpg for postgres URLs that omit the dialect.
if _url.drivername.startswith("postgresql") and "+asyncpg" not in _url.drivername:
    _url = _url.set(drivername="postgresql+asyncpg")


def _build_async_connect_args(
    drivername: str,
    environment: str,
    command_timeout_s: float,
    through_pgbouncer: bool,
) -> dict:
    """asyncpg ``connect_args`` for the async engine.

    Adds a per-statement ``command_timeout`` (DoS backstop, ARCH-016 follow-up)
    and, in production, ``ssl=require``. Only applies to postgresql/asyncpg —
    other drivers (e.g. aiosqlite in tests) reject these kwargs, so they get
    an empty dict.

    When ``through_pgbouncer`` (Tier E madde 30), forces anonymous
    (unnamed) prepared statements — required for correctness under PgBouncer
    transaction pooling (see DB_THROUGH_PGBOUNCER docstring in app/config.py
    for why).

    Disabling SQLAlchemy's ``prepared_statement_cache_size`` alone is NOT
    sufficient: even with the cache off, ``AsyncAdapt_asyncpg_connection._prepare``
    still calls ``asyncpg_connection.prepare(operation, name=<autogenerated>)``
    with a NAMED statement (``__asyncpg_stmt_N__``, a per-connection-object
    counter starting at 1). Under PgBouncer transaction pooling, a backend
    connection is shared across many client-side asyncpg connection objects,
    each with its own counter — two different clients both requesting
    "__asyncpg_stmt_1__" on the same recycled backend connection collide with
    ``asyncpg.exceptions.DuplicatePreparedStatementError``. The actual fix is
    ``prepared_statement_name_func`` returning ``""`` on every call, which
    makes asyncpg issue an anonymous (unnamed) prepared statement — those are
    scoped to the single extended-query round trip and never persist on the
    backend connection, so they can never collide. Proven via a 50-concurrent-
    connection isolated repro against the live pgbouncer service (Tier E
    madde 30); ``statement_cache_size``/``prepared_statement_cache_size=0``
    alone still failed 5/30 concurrent requests.
    """
    if not drivername.startswith("postgresql"):
        return {}
    args: dict = {}
    if command_timeout_s and command_timeout_s > 0:
        args["command_timeout"] = command_timeout_s
    if environment == "prod":
        args["ssl"] = "require"
    if through_pgbouncer:
        args["statement_cache_size"] = 0
        args["prepared_statement_cache_size"] = 0
        args["prepared_statement_name_func"] = lambda: ""
    return args


_engine_kwargs = dict(
    echo=settings.SQL_ECHO,
    future=True,
    pool_pre_ping=True,
    pool_size=settings.DB_POOL_SIZE,  # ARCH-005: configurable (default 40)
    max_overflow=settings.DB_MAX_OVERFLOW,  # ARCH-005: configurable (default 5)
    pool_timeout=60,  # Increased from 30 to reduce timeout errors
    pool_recycle=900,  # Reduced from 1800 to recycle idle connections more frequently
    pool_reset_on_return="rollback",  # Reset session state on return
)
_async_connect_args = _build_async_connect_args(
    _url.drivername,
    settings.ENVIRONMENT,
    settings.DB_COMMAND_TIMEOUT_S,
    settings.DB_THROUGH_PGBOUNCER,
)
if _async_connect_args:
    _engine_kwargs["connect_args"] = _async_connect_args

engine = create_async_engine(_url, **_engine_kwargs)

AsyncSessionLocal = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
    autoflush=False,
)


# ── FastAPI dependency ────────────────────────────────────────────────────────
async def get_db() -> AsyncIterator[AsyncSession]:
    """Yield an async session. Rolls back on exception, always closes."""
    async with AsyncSessionLocal() as session:
        try:
            yield session
        except Exception:
            await session.rollback()
            raise


@asynccontextmanager
async def session_scope() -> AsyncIterator[AsyncSession]:
    """Async context manager: commit on success, rollback on error, always close."""
    async with AsyncSessionLocal() as session:
        try:
            yield session
            await session.commit()
        except Exception:
            await session.rollback()
            raise


# ── Sync wrapper (ARCH-005: no separate pool — reuses async engine's internal sync engine)
# Production code must not use this for request-path SQL; it exists for
# scripts (benchmark.py) and test fixtures (conftest.py patches SyncSessionLocal).
sync_engine = engine.sync_engine
SyncSessionLocal = sessionmaker(bind=sync_engine, autocommit=False, autoflush=False)


@contextmanager
def get_sync_session() -> Iterator[Session]:
    """Sync session — auto-commits on success, rolls back on error."""
    session = SyncSessionLocal()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


# Legacy alias kept for `app.scripts.benchmark`.
get_connection = get_sync_session
