"""add_is_deleted_flags_v2_1

Revision ID: 9728f5747de4
Revises: 0003_route_path_cache_contract
Create Date: 2026-04-08 10:15:57.765032

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9728f5747de4"
down_revision: Union[str, Sequence[str], None] = "0003_route_path_cache_contract"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_outbox_created", "outbox_events", ["created_at"], unique=False)
    op.create_index(
        "idx_outbox_processed", "outbox_events", ["processed"], unique=False
    )
    op.create_table(
        "vehicle_spec_timeline",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("arac_id", sa.Integer(), nullable=False),
        sa.Column("dingil_sayisi", sa.Integer(), nullable=False),
        sa.Column("yakit_tipi", sa.String(length=20), nullable=False),
        sa.Column("bos_agirlik_kg", sa.Integer(), nullable=False),
        sa.Column("kapasite_kg", sa.Integer(), nullable=False),
        sa.Column(
            "gecerlilik_tarihi",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("degistiren_id", sa.Integer(), nullable=True),
        sa.Column("notlar", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["arac_id"], ["araclar.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["degistiren_id"],
            ["kullanicilar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_spec_arac_tarih",
        "vehicle_spec_timeline",
        ["arac_id", "gecerlilik_tarihi"],
        unique=False,
    )
    op.alter_column(
        "admin_audit_log",
        "eski_deger",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "admin_audit_log",
        "yeni_deger",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "admin_audit_log",
        "ip_adresi",
        existing_type=postgresql.INET(),
        type_=sa.String(length=45),
        existing_nullable=True,
    )
    op.add_column(
        "araclar",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "araclar", sa.Column("onay_tarihi", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("araclar", sa.Column("olusturan_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_araclar_is_deleted"), "araclar", ["is_deleted"], unique=False
    )
    op.create_foreign_key(None, "araclar", "kullanicilar", ["olusturan_id"], ["id"])
    op.drop_column("araclar", "updated_at")
    op.alter_column(
        "bildirim_kurallari",
        "kanallar",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=sa.JSON(),
        existing_nullable=False,
        postgresql_using="array_to_json(kanallar)::json",
    )
    op.add_column(
        "dorseler",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_dorseler_is_deleted"), "dorseler", ["is_deleted"], unique=False
    )
    op.alter_column(
        "iceri_aktarim_gecmisi",
        "islem_haritasi",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "iceri_aktarim_gecmisi",
        "hatalar",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "iceri_aktarim_gecmisi",
        "rollback_baglantilari",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "konfig_gecmis",
        "eski_deger",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "konfig_gecmis",
        "yeni_deger",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "kullanici_ayarlari",
        "deger",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "kullanici_oturumlari",
        "ip_adresi",
        existing_type=postgresql.INET(),
        type_=sa.String(length=45),
        existing_nullable=False,
    )
    op.alter_column(
        "kullanicilar",
        "son_giris_ip",
        existing_type=postgresql.INET(),
        type_=sa.String(length=45),
        existing_nullable=True,
    )
    op.add_column(
        "lokasyonlar",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_lokasyonlar_is_deleted"), "lokasyonlar", ["is_deleted"], unique=False
    )
    op.alter_column(
        "model_versiyonlar",
        "kullanilan_ozellikler",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "roller",
        "yetkiler",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    # Guard against DuplicateColumn: 0003_route_path_cache_contract already
    # adds otoban_mesafe_km and sehir_ici_mesafe_km.  Use IF NOT EXISTS so the
    # migration is idempotent regardless of which prior migrations have run.
    op.execute(
        "ALTER TABLE route_paths ADD COLUMN IF NOT EXISTS otoban_mesafe_km FLOAT"
    )
    op.execute(
        "ALTER TABLE route_paths ADD COLUMN IF NOT EXISTS sehir_ici_mesafe_km FLOAT"
    )
    op.execute(
        "ALTER TABLE route_paths ADD COLUMN IF NOT EXISTS difficulty VARCHAR(20)"
    )
    op.execute("ALTER TABLE route_paths ADD COLUMN IF NOT EXISTS route_analysis JSON")
    op.add_column(
        "seferler", sa.Column("route_pair_id", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "seferler",
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    op.alter_column(
        "seferler", "guzergah_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_index(
        op.f("ix_seferler_route_pair_id"), "seferler", ["route_pair_id"], unique=False
    )
    # Drop the guzergah_id FK regardless of which name it was created with.
    # Baseline (0001) may have used PostgreSQL's default name or the Alembic
    # naming convention; use a DO block to handle both cases idempotently.
    op.execute("""
        DO $$
        DECLARE r RECORD;
        BEGIN
            FOR r IN
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                   AND tc.table_name = kcu.table_name
                WHERE tc.constraint_type = 'FOREIGN KEY'
                  AND tc.table_name = 'seferler'
                  AND kcu.column_name = 'guzergah_id'
            LOOP
                EXECUTE 'ALTER TABLE seferler DROP CONSTRAINT ' || quote_ident(r.constraint_name);
            END LOOP;
        END $$
    """)
    op.create_foreign_key(
        "fk_seferler_guzergah_id_lokasyonlar",
        "seferler",
        "lokasyonlar",
        ["guzergah_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("seferler", "is_real")
    op.alter_column(
        "sistem_konfig",
        "deger",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.add_column(
        "yakit_alimlari", sa.Column("route_analysis", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("yakit_alimlari", "route_analysis")
    op.alter_column(
        "sistem_konfig",
        "deger",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.add_column(
        "seferler",
        sa.Column("is_real", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.execute("""
        DO $$
        DECLARE r RECORD;
        BEGIN
            FOR r IN
                SELECT tc.constraint_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                    ON tc.constraint_name = kcu.constraint_name
                   AND tc.table_name = kcu.table_name
                WHERE tc.constraint_type = 'FOREIGN KEY'
                  AND tc.table_name = 'seferler'
                  AND kcu.column_name = 'guzergah_id'
            LOOP
                EXECUTE 'ALTER TABLE seferler DROP CONSTRAINT ' || quote_ident(r.constraint_name);
            END LOOP;
        END $$
    """)
    op.create_foreign_key(
        op.f("seferler_guzergah_id_fkey"),
        "seferler",
        "lokasyonlar",
        ["guzergah_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_seferler_route_pair_id"), table_name="seferler")
    op.alter_column(
        "seferler", "guzergah_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("seferler", "version")
    op.drop_column("seferler", "route_pair_id")
    op.drop_column("route_paths", "route_analysis")
    op.drop_column("route_paths", "difficulty")
    op.drop_column("route_paths", "sehir_ici_mesafe_km")
    op.drop_column("route_paths", "otoban_mesafe_km")
    op.alter_column(
        "roller",
        "yetkiler",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "model_versiyonlar",
        "kullanilan_ozellikler",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_lokasyonlar_is_deleted"), table_name="lokasyonlar")
    op.drop_column("lokasyonlar", "is_deleted")
    op.alter_column(
        "kullanicilar",
        "son_giris_ip",
        existing_type=sa.String(length=45),
        type_=postgresql.INET(),
        existing_nullable=True,
    )
    op.alter_column(
        "kullanici_oturumlari",
        "ip_adresi",
        existing_type=sa.String(length=45),
        type_=postgresql.INET(),
        existing_nullable=False,
    )
    op.alter_column(
        "kullanici_ayarlari",
        "deger",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "konfig_gecmis",
        "yeni_deger",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "konfig_gecmis",
        "eski_deger",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.alter_column(
        "iceri_aktarim_gecmisi",
        "rollback_baglantilari",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "iceri_aktarim_gecmisi",
        "hatalar",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "iceri_aktarim_gecmisi",
        "islem_haritasi",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_dorseler_is_deleted"), table_name="dorseler")
    op.drop_column("dorseler", "is_deleted")
    op.alter_column(
        "bildirim_kurallari",
        "kanallar",
        existing_type=sa.JSON(),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
    )
    op.add_column(
        "araclar",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "araclar", type_="foreignkey")
    op.drop_index(op.f("ix_araclar_is_deleted"), table_name="araclar")
    op.drop_column("araclar", "olusturan_id")
    op.drop_column("araclar", "onay_tarihi")
    op.drop_column("araclar", "is_deleted")
    op.alter_column(
        "admin_audit_log",
        "ip_adresi",
        existing_type=sa.String(length=45),
        type_=postgresql.INET(),
        existing_nullable=True,
    )
    op.alter_column(
        "admin_audit_log",
        "yeni_deger",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "admin_audit_log",
        "eski_deger",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index("idx_spec_arac_tarih", table_name="vehicle_spec_timeline")
    op.drop_table("vehicle_spec_timeline")
    op.drop_index("idx_outbox_processed", table_name="outbox_events")
    op.drop_index("idx_outbox_created", table_name="outbox_events")
    op.drop_table("outbox_events")
    # ### end Alembic commands ###
