"""add idx_anomaly_kaynak index (fix schema drift)

Revision ID: bc35e04ad0fd
Revises: 0021_fix_partition
Create Date: 2026-06-09 10:27:00.118763

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc35e04ad0fd"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "0021_fix_partition"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_anomaly_kaynak", "anomalies", ["kaynak_tip", "kaynak_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_anomaly_kaynak", table_name="anomalies")
    # ### end Alembic commands ###
