export const coachingPageText = {
  heading: "Coaching Module",
  description: "AI-powered driver behavior analysis and recommendations.",
  emptyDriverList: "No active drivers found.",
  selectDriverHint: "Select a driver from the left panel to see details.",
  sourceLlm: "Generated by AI",
  sourceFallback: "Rule-based (LLM fallback)",
  refresh: "Refresh",
  errorLoad: "Recommendations could not be loaded",
  emptyInsights: "No active recommendations for this driver",
} as const;

export const coachingCategoryLabels: Record<string, string> = {
  yakit_yonetimi: "Fuel Management",
  guzergah_tercihi: "Route Preference",
  sofor_pratigi: "Driving Practice",
  diger: "Other",
} as const;

export const coachingPriorityLabels: Record<string, string> = {
  low: "Low",
  medium: "Medium",
  high: "High",
} as const;

export const sendCoachingDialogText = {
  title: "Send Coaching via Telegram",
  subtitle: (name: string) => `To driver ${name}`,
  messageLabel: "Message",
  messagePlaceholder: "Edit your recommendation...",
  minLength: "Message must be at least 10 characters.",
  maxLength: "Message cannot exceed 1000 characters.",
  sendButton: "Send via Telegram",
  cancel: "Cancel",
  successTitle: "Sent",
  successMessage: "Message sent via Telegram.",
  errorTitle: "Error",
  errorMessage: "Message could not be sent.",
  notRegisteredTitle: "Driver not registered on Telegram",
  notRegisteredMessage:
    "This driver is not paired with the Telegram bot; message cannot be sent.",
} as const;

export const coachingDriverListText = {
  heading: "Drivers",
  searchPlaceholder: "Search...",
  aktifOnly: "Active only",
} as const;
