export const investigationsText = {
  tabLabel: "Investigations",
  sectionTitle: "Fuel Theft Investigations",
  emptyKanban: "No investigations yet.",
  columnLabels: {
    open: "Open",
    assigned: "Assigned",
    investigating: "Investigating",
    resolved: "Resolved",
    closed: "Closed",
  },
  suspicionLabels: {
    low: "Low",
    medium: "Medium",
    high: "High",
    unknown: "Unknown",
  },
  resolutionLabels: {
    real_theft: "Real theft",
    false_alarm: "False alarm",
    data_error: "Data error",
    inconclusive: "Inconclusive",
  },
  actions: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    delete: "Close investigation",
    addEvidence: "+ Add URL",
  },
  fields: {
    status: "Status",
    suspicion: "Suspicion",
    score: "Score",
    assigned: "Assigned",
    notes: "Notes",
    resolution: "Resolution Type",
    evidence: "Evidence (URL list)",
    plaka: "Plate",
    sofor: "Driver",
    sapma: "Deviation",
    created: "Created",
  },
  notRegistered: "— unassigned —",
  successUpdate: "Investigation updated.",
  errorUpdate: "Could not be updated.",
  confirmClose: "Are you sure you want to close this investigation?",
  successClose: "Investigation closed.",
  pattern: {
    title: "Recurring Patterns",
    subtitle: (days: number) => `Last ${days} days — ≥ N events`,
    minCountLabel: "Min events",
    daysLabel: "Window (days)",
    empty: "No recurring patterns found.",
    columns: {
      sofor: "Driver",
      plaka: "Plate",
      count: "Events",
      avgScore: "Avg. Score",
      lastSeen: "Last",
    },
  },
} as const;
