export const maintenancePredictionsText = {
  tabs: {
    list: "List",
    calendar: "Calendar",
    history: "History",
    muayene: "Inspection",
  },
  inspection: {
    vehicles: "Vehicles",
    trailers: "Trailers",
    overdue: "Inspection Overdue",
    expiring: "Inspection Due Soon",
    daysOverdue: (n: number) => `${Math.abs(n)} days overdue`,
    daysLeft: (n: number) => `${n} days left`,
    noAlerts: "No inspection alerts.",
    loadFailed: "Failed to load inspection data.",
  },
  breakdown: {
    title: "Report Breakdown",
    targetLabel: "Type",
    vehicle: "Vehicle",
    trailer: "Trailer",
    selectVehicle: "Select a vehicle…",
    selectTrailer: "Select a trailer…",
    urgencyLabel: "Urgency",
    urgent: "Urgent",
    fault: "Breakdown",
    kmLabel: "Mileage (optional)",
    descriptionLabel: "Description",
    descriptionPlaceholder: "What is the issue?",
    cancel: "Cancel",
    submitting: "Submitting…",
    submit: "Report",
    errVehicleRequired: "Please select a vehicle.",
    errTrailerRequired: "Please select a trailer.",
    errGeneric: "Could not report breakdown.",
    successTitle: "Breakdown reported",
    successBody: "An open breakdown record was created.",
  },
  pageTitle: "Predictive Maintenance",
  calendarLegend: {
    overdue: "Overdue",
    soon: "Soon",
    normal: "Normal",
    low: "Low risk",
    unpredictable: "No prediction",
  },
  riskLabels: {
    overdue: "Overdue",
    soon: "Soon",
    normal: "Normal",
    low: "Low",
  } as const,
  table: {
    columns: {
      plaka: "Plate",
      bakim_tipi: "Maintenance Type",
      predicted_date: "Predicted Date",
      days_remaining: "Days Remaining",
      risk_level: "Risk",
      confidence: "Confidence",
      savings: "Savings",
      actions: "Actions",
    },
    empty: "No predictable maintenance yet.",
    unpredictable: "Insufficient data for prediction",
    notApplicable: "—",
    downloadIcs: "Add to Calendar",
  },
  drawer: {
    title: "Maintenance Prediction Detail",
    sections: {
      summary: "Summary",
      reasons: "Reasons",
      actions: "Actions",
    },
    labels: {
      plaka: "Plate",
      bakim_tipi: "Maintenance Type",
      predicted_date: "Predicted Date",
      days_remaining: "Days Remaining",
      confidence: "Confidence",
      risk: "Risk",
      savings: "Estimated Savings",
    },
    downloadIcs: "Download to Calendar (.ics)",
    close: "Close",
    notPredictable:
      "Insufficient data for this vehicle; prediction cannot be generated.",
    downloadError: "Calendar file could not be downloaded.",
  },
  errors: {
    loadFailed: "Predictions could not be loaded.",
    flagOff: "Maintenance prediction module is disabled.",
    forbidden: "You do not have permission for this operation.",
  },
} as const;
