export const dataTransferText = {
  toolbarButton: "Excel Operations",
  uploadActionTitle: "Upload from Excel",
  uploadActionDescription: "Import module",
  templateActionTitle: "Sample Template",
  templateActionDescription: "Download template",
  exportActionTitle: "Export",
  exportActionDescription: "Export all records to Excel",
  uploadModal: {
    title: "Import Excel Records",
    description: "Drag your file here or click to select (.xlsx, .xls)",
    invalidFileType: "Please upload only Excel (.xlsx, .xls) files.",
    invalidFileError: "Invalid file format.",
    processing: "Processing file...",
    success: "File uploaded successfully!",
    changeFile: "Change File",
    idle: "Click or drag to upload",
    allowedFormats: "Allowed file types: .xlsx, .xls",
    uploadErrorFallback: "An error occurred during upload.",
    uploadErrorDetected: "Some errors were detected while uploading the file.",
    row: "Row",
    field: "Field",
    errorReason: "Error Reason",
    processed: "Processed",
    saved: "Successful",
    failed: "Failed",
    cancel: "Cancel",
    startUpload: "Start Upload",
  },
} as const;
