"""018_maintenance_system

Revision ID: 018_maintenance
Revises: a20_route_calibration
Create Date: 2026-02-28 13:40:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "018_maintenance"
down_revision = "a20_route_calib"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if "arac_bakimlari" not in inspector.get_table_names():
        op.create_table(
            "arac_bakimlari",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("arac_id", sa.Integer(), nullable=False),
            sa.Column("bakim_tipi", sa.String(length=20), nullable=False),
            sa.Column("km_bilgisi", sa.Integer(), nullable=False),
            sa.Column(
                "bakim_tarihi",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column("maliyet", sa.Numeric(precision=10, scale=2), nullable=False),
            sa.Column("detaylar", sa.Text(), nullable=True),
            sa.Column("tamamlandi", sa.Boolean(), nullable=False),
            sa.Column(
                "olusturma_tarihi",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["arac_id"], ["araclar.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_arac_bakimlari_arac_id"),
            "arac_bakimlari",
            ["arac_id"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_arac_bakimlari_arac_id"), table_name="arac_bakimlari")
    op.drop_table("arac_bakimlari")
    # ### end Alembic commands ###
