"""021_notification_engine

Revision ID: 021_notification
Revises: 018_maintenance
Create Date: 2026-02-28 13:50:00.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "021_notification"
down_revision = "018_maintenance"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "bildirim_kurallari" not in inspector.get_table_names():
        op.create_table(
            "bildirim_kurallari",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("olay_tipi", sa.String(length=50), nullable=False),
            sa.Column("kanallar", postgresql.ARRAY(sa.String()), nullable=False),
            sa.Column("alici_rol_id", sa.Integer(), nullable=False),
            sa.Column("aktif", sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_bildirim_kurallari_olay_tipi"),
            "bildirim_kurallari",
            ["olay_tipi"],
            unique=False,
        )

    if "bildirim_gecmisi" not in inspector.get_table_names():
        op.create_table(
            "bildirim_gecmisi",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("kullanici_id", sa.Integer(), nullable=False),
            sa.Column("baslik", sa.String(length=200), nullable=False),
            sa.Column("icerik", sa.Text(), nullable=False),
            sa.Column("kanal", sa.String(length=20), nullable=False),
            sa.Column("durum", sa.String(length=20), nullable=False),
            sa.Column("okundu_tarihi", sa.DateTime(), nullable=True),
            sa.Column(
                "olusturma_tarihi",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(
                ["kullanici_id"], ["kullanicilar.id"], ondelete="CASCADE"
            ),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_bildirim_gecmisi_kullanici_id"),
            "bildirim_gecmisi",
            ["kullanici_id"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bildirim_gecmisi_kullanici_id"), table_name="bildirim_gecmisi"
    )
    op.drop_table("bildirim_gecmisi")
    op.drop_index(
        op.f("ix_bildirim_kurallari_olay_tipi"), table_name="bildirim_kurallari"
    )
    op.drop_table("bildirim_kurallari")
    # ### end Alembic commands ###
