"""add_guzergah_update_sefer

Revision ID: 0a1e4023a1cb
Revises: 4e9f3060b152
Create Date: 2026-02-01 20:39:13.104832

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a1e4023a1cb"
down_revision: Union[str, Sequence[str], None] = "4e9f3060b152"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("seferler_arac_id_fkey"), "seferler", type_="foreignkey")
    op.drop_constraint(op.f("seferler_sofor_id_fkey"), "seferler", type_="foreignkey")
    op.create_foreign_key(
        None, "seferler", "araclar", ["arac_id"], ["id"], ondelete="RESTRICT"
    )
    op.create_foreign_key(
        None, "seferler", "soforler", ["sofor_id"], ["id"], ondelete="RESTRICT"
    )
    op.add_column(
        "soforler",
        sa.Column(
            "manual_score", sa.Float(), nullable=False, server_default=sa.text("1.0")
        ),
    )
    op.create_index(op.f("ix_soforler_ad_soyad"), "soforler", ["ad_soyad"], unique=True)
    op.drop_constraint(
        op.f("yakit_alimlari_arac_id_fkey"), "yakit_alimlari", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "yakit_alimlari", "araclar", ["arac_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(
        op.f("yakit_formul_arac_id_fkey"), "yakit_formul", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "yakit_formul", "araclar", ["arac_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_constraint(
        op.f("yakit_periyotlari_arac_id_fkey"), "yakit_periyotlari", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "yakit_periyotlari", "araclar", ["arac_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "yakit_periyotlari", type_="foreignkey")
    op.create_foreign_key(
        op.f("yakit_periyotlari_arac_id_fkey"),
        "yakit_periyotlari",
        "araclar",
        ["arac_id"],
        ["id"],
    )
    op.drop_constraint(None, "yakit_formul", type_="foreignkey")
    op.create_foreign_key(
        op.f("yakit_formul_arac_id_fkey"),
        "yakit_formul",
        "araclar",
        ["arac_id"],
        ["id"],
    )
    op.drop_constraint(None, "yakit_alimlari", type_="foreignkey")
    op.create_foreign_key(
        op.f("yakit_alimlari_arac_id_fkey"),
        "yakit_alimlari",
        "araclar",
        ["arac_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_soforler_ad_soyad"), table_name="soforler")
    op.drop_column("soforler", "manual_score")
    op.drop_constraint(None, "seferler", type_="foreignkey")
    op.drop_constraint(None, "seferler", type_="foreignkey")
    op.create_foreign_key(
        op.f("seferler_sofor_id_fkey"), "seferler", "soforler", ["sofor_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("seferler_arac_id_fkey"), "seferler", "araclar", ["arac_id"], ["id"]
    )
    # ### end Alembic commands ###
