"""019_import_history

Revision ID: 0fd51bbb32e2
Revises: ef8abc3ede67
Create Date: 2026-02-28 12:50:52.427042

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fd51bbb32e2"
down_revision: Union[str, Sequence[str], None] = "ef8abc3ede67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "iceri_aktarim_gecmisi",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("dosya_adi", sa.String(length=255), nullable=False),
        sa.Column("aktarim_tipi", sa.String(length=50), nullable=False),
        sa.Column("durum", sa.String(length=50), nullable=False),
        sa.Column("toplam_kayit", sa.Integer(), nullable=False),
        sa.Column("basarili_kayit", sa.Integer(), nullable=False),
        sa.Column("hatali_kayit", sa.Integer(), nullable=False),
        sa.Column(
            "islem_haritasi", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("hatalar", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("yukleyen_id", sa.Integer(), nullable=True),
        sa.Column(
            "baslama_zamani",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("bitis_zamani", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "rollback_baglantilari",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["yukleyen_id"],
            ["kullanicilar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_iceri_aktarim_gecmisi_aktarim_tipi"),
        "iceri_aktarim_gecmisi",
        ["aktarim_tipi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_iceri_aktarim_gecmisi_durum"),
        "iceri_aktarim_gecmisi",
        ["durum"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_iceri_aktarim_gecmisi_durum"), table_name="iceri_aktarim_gecmisi"
    )
    op.drop_index(
        op.f("ix_iceri_aktarim_gecmisi_aktarim_tipi"),
        table_name="iceri_aktarim_gecmisi",
    )
    op.drop_table("iceri_aktarim_gecmisi")
    # ### end Alembic commands ###
