"""seferler_denetim_1

Revision ID: 2309c90b0151
Revises: 9d34165ea0de
Create Date: 2026-03-04 14:29:29.118160

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2309c90b0151"
down_revision: Union[str, Sequence[str], None] = "9d34165ea0de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kullanici_ayarlari",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kullanici_id", sa.Integer(), nullable=False),
        sa.Column("modul", sa.String(length=50), nullable=False),
        sa.Column("ayar_tipi", sa.String(length=50), nullable=False),
        sa.Column("deger", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("ad", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kullanici_id"], ["kullanicilar.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kullanici_ayarlari_ayar_tipi"),
        "kullanici_ayarlari",
        ["ayar_tipi"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kullanici_ayarlari_kullanici_id"),
        "kullanici_ayarlari",
        ["kullanici_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kullanici_ayarlari_modul"),
        "kullanici_ayarlari",
        ["modul"],
        unique=False,
    )
    op.add_column(
        "bildirim_gecmisi", sa.Column("olay_tipi", sa.String(length=50), nullable=True)
    )
    op.create_index(
        op.f("ix_bildirim_gecmisi_olay_tipi"),
        "bildirim_gecmisi",
        ["olay_tipi"],
        unique=False,
    )
    op.add_column(
        "seferler",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.execute("DROP INDEX IF EXISTS idx_seferler_arac_tarih")
    op.execute("DROP INDEX IF EXISTS idx_seferler_durum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_seferler_durum"), "seferler", ["durum"], unique=False)
    op.create_index(
        op.f("idx_seferler_arac_tarih"), "seferler", ["arac_id", "tarih"], unique=False
    )
    op.drop_column("seferler", "updated_at")
    op.drop_index(op.f("ix_bildirim_gecmisi_olay_tipi"), table_name="bildirim_gecmisi")
    op.drop_column("bildirim_gecmisi", "olay_tipi")
    op.drop_index(op.f("ix_kullanici_ayarlari_modul"), table_name="kullanici_ayarlari")
    op.drop_index(
        op.f("ix_kullanici_ayarlari_kullanici_id"), table_name="kullanici_ayarlari"
    )
    op.drop_index(
        op.f("ix_kullanici_ayarlari_ayar_tipi"), table_name="kullanici_ayarlari"
    )
    op.drop_table("kullanici_ayarlari")
    # ### end Alembic commands ###
