"""add_aktif_flag_for_soft_delete

Revision ID: 4e9f3060b152
Revises: cba4911a4a05
Create Date: 2026-01-20 23:53:17.598788

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e9f3060b152"
down_revision: Union[str, Sequence[str], None] = "cba4911a4a05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default=True for existing rows
    op.add_column(
        "lokasyonlar",
        sa.Column(
            "aktif", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    op.add_column(
        "seferler",
        sa.Column(
            "aktif", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    # Skip index creation - already exists or has duplicates
    # op.create_index(op.f('ix_soforler_ad_soyad'), 'soforler', ['ad_soyad'], unique=True)
    op.add_column(
        "yakit_alimlari",
        sa.Column(
            "aktif", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("yakit_alimlari", "aktif")
    # op.drop_index(op.f('ix_soforler_ad_soyad'), table_name='soforler')
    op.drop_column("seferler", "aktif")
    op.drop_column("lokasyonlar", "aktif")
    # ### end Alembic commands ###
