"""add_triggered_by_to_vehicle_event_log

Revision ID: 5144dc178795
Revises: 7b90f4d92369
Create Date: 2026-02-19 21:15:23.907139

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5144dc178795"
down_revision: Union[str, Sequence[str], None] = "7b90f4d92369"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_event_log",
        sa.Column("triggered_by", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_vehicle_event_log_triggered_by"),
        "vehicle_event_log",
        ["triggered_by"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vehicle_event_log_triggered_by"), table_name="vehicle_event_log"
    )
    op.drop_column("vehicle_event_log", "triggered_by")
    # ### end Alembic commands ###
