"""Update mesafe_km type to float

Revision ID: 5c83e424a0f3
Revises: a3214dd89c76
Create Date: 2026-02-03 21:18:59.567987

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c83e424a0f3"
down_revision: Union[str, Sequence[str], None] = "a3214dd89c76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('guzergahlar', 'mesafe_km',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Float(),
    #            existing_nullable=False)
    op.alter_column(
        "lokasyonlar",
        "mesafe_km",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "seferler",
        "mesafe_km",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "seferler",
        "mesafe_km",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "lokasyonlar",
        "mesafe_km",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "guzergahlar",
        "mesafe_km",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
