"""add gin index to seferler rota_detay

Revision ID: 70b160f9c4ff
Revises: d90a84ac7510
Create Date: 2026-03-04 08:55:39.204538

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70b160f9c4ff"
down_revision: Union[str, Sequence[str], None] = "d90a84ac7510"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE seferler ALTER COLUMN rota_detay TYPE JSONB USING rota_detay::jsonb"
    )
    op.create_index(
        "idx_seferler_rota_detay_gin",
        "seferler",
        ["rota_detay"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_seferler_rota_detay_gin", table_name="seferler")
    op.execute(
        "ALTER TABLE seferler ALTER COLUMN rota_detay TYPE JSON USING rota_detay::json"
    )
    # ### end Alembic commands ###
