"""drop_guzergahlar_table

Revision ID: 73752c1be58c
Revises: f93d33b10f23
Create Date: 2026-02-15 12:32:09.940763

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73752c1be58c"
down_revision: Union[str, Sequence[str], None] = "f93d33b10f23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_guzergahlar_ad'), table_name='guzergahlar')
    # op.drop_table('guzergahlar')

    # Ensure model_versions exists
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("arac_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("model_type", sa.String(length=50), nullable=False),
        sa.Column("params_json", sa.Text(), nullable=False),
        sa.Column("r2_score", sa.Float(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column(
            "sample_count", sa.Integer(), server_default=sa.text("0"), nullable=True
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("false"), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        # Columns that might be dropped in later migrations
        sa.Column("feature_schema_hash", sa.String(length=64), nullable=True),
        sa.Column("physics_version", sa.String(length=50), nullable=True),
        sa.Column("training_data_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["arac_id"], ["araclar.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_model_versions_arac_id", "model_versions", ["arac_id"], unique=False
    )
    op.alter_column(
        "lokasyonlar",
        "aktif",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    # op.drop_column("lokasyonlar", "route_analysis")
    op.add_column("seferler", sa.Column("otoban_mesafe_km", sa.Float(), nullable=True))
    op.add_column(
        "seferler", sa.Column("sehir_ici_mesafe_km", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seferler", "sehir_ici_mesafe_km")
    op.drop_column("seferler", "otoban_mesafe_km")
    op.add_column(
        "lokasyonlar",
        sa.Column(
            "route_analysis",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "lokasyonlar",
        "aktif",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    # op.create_table(
    #     "model_versions",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("arac_id", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         "model_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
    #     ),
    #     sa.Column("params_json", sa.TEXT(), autoincrement=False, nullable=False),
    #     sa.Column(
    #         "r2_score",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "mae", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
    #     ),
    #     sa.Column(
    #         "sample_count",
    #         sa.INTEGER(),
    #         server_default=sa.text("0"),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "is_active",
    #         sa.BOOLEAN(),
    #         server_default=sa.text("false"),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "created_at",
    #         postgresql.TIMESTAMP(),
    #         server_default=sa.text("now()"),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
    #     sa.PrimaryKeyConstraint("id", name=op.f("model_versions_pkey")),
    # )
    # op.create_index(
    #     op.f("idx_model_versions_arac_id"), "model_versions", ["arac_id"], unique=False
    # )
    # op.create_table(
    #     "guzergahlar",
    #     sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    #     sa.Column("ad", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    #     sa.Column(
    #         "cikis_yeri", sa.VARCHAR(length=100), autoincrement=False, nullable=False
    #     ),
    #     sa.Column(
    #         "varis_yeri", sa.VARCHAR(length=100), autoincrement=False, nullable=False
    #     ),
    #     sa.Column(
    #         "mesafe_km",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "varsayilan_arac_id", sa.INTEGER(), autoincrement=False, nullable=True
    #     ),
    #     sa.Column(
    #         "varsayilan_sofor_id", sa.INTEGER(), autoincrement=False, nullable=True
    #     ),
    #     sa.Column("notlar", sa.TEXT(), autoincrement=False, nullable=True),
    #     sa.Column(
    #         "created_at",
    #         postgresql.TIMESTAMP(),
    #         server_default=sa.text("now()"),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "cikis_lat",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "cikis_lon",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "varis_lat",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "varis_lon",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "ascent_m",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "descent_m",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.Column(
    #         "flat_distance_km",
    #         sa.DOUBLE_PRECISION(precision=53),
    #         autoincrement=False,
    #         nullable=False,
    #     ),
    #     sa.Column(
    #         "geometry",
    #         postgresql.JSON(astext_type=sa.Text()),
    #         autoincrement=False,
    #         nullable=True,
    #     ),
    #     sa.ForeignKeyConstraint(
    #         ["varsayilan_arac_id"],
    #         ["araclar.id"],
    #         name=op.f("guzergahlar_varsayilan_arac_id_fkey"),
    #         ondelete="SET NULL",
    #     ),
    #     sa.ForeignKeyConstraint(
    #         ["varsayilan_sofor_id"],
    #         ["soforler.id"],
    #         name=op.f("guzergahlar_varsayilan_sofor_id_fkey"),
    #         ondelete="SET NULL",
    #     ),
    #     sa.PrimaryKeyConstraint("id", name=op.f("guzergahlar_pkey")),
    # )
    # op.create_index(op.f("ix_guzergahlar_ad"), "guzergahlar", ["ad"], unique=True)
    # ### end Alembic commands ###
