"""add_vehicle_event_log

Revision ID: 7b90f4d92369
Revises: a58e2561f362
Create Date: 2026-02-19 17:48:56.580032

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b90f4d92369"
down_revision: Union[str, Sequence[str], None] = "a58e2561f362"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Defensive: Add missing columns if they were skipped in earlier messy migrations
    # lokasyonlar
    op.add_column(
        "lokasyonlar",
        sa.Column(
            "is_corrected",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # seferler
    op.add_column(
        "seferler", sa.Column("sefer_no", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "seferler",
        sa.Column(
            "flat_distance_km",
            sa.Float(),
            server_default=sa.text("0.0"),
            nullable=False,
        ),
    )
    op.add_column("seferler", sa.Column("duration_min", sa.Integer(), nullable=True))
    op.add_column("seferler", sa.Column("notlar", sa.String(length=255), nullable=True))
    op.add_column(
        "seferler",
        sa.Column(
            "is_real", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # yakit_alimlari
    op.add_column(
        "yakit_alimlari", sa.Column("saat", sa.String(length=5), nullable=True)
    )
    op.add_column(
        "yakit_alimlari", sa.Column("red_nedeni", sa.String(length=255), nullable=True)
    )
    # soforler
    op.add_column(
        "soforler",
        sa.Column(
            "hiz_disiplin_skoru",
            sa.Float(),
            server_default=sa.text("1.0"),
            nullable=False,
        ),
    )
    op.add_column(
        "soforler",
        sa.Column(
            "agresif_surus_faktoru",
            sa.Float(),
            server_default=sa.text("1.0"),
            nullable=False,
        ),
    )  # araclar (Elite Technical Specs)
    op.add_column(
        "araclar",
        sa.Column(
            "bos_agirlik_kg",
            sa.Float(),
            server_default=sa.text("8000.0"),
            nullable=False,
        ),
    )
    op.add_column(
        "araclar",
        sa.Column(
            "hava_direnc_katsayisi",
            sa.Float(),
            server_default=sa.text("0.7"),
            nullable=False,
        ),
    )
    op.add_column(
        "araclar",
        sa.Column(
            "on_kesit_alani_m2",
            sa.Float(),
            server_default=sa.text("8.5"),
            nullable=False,
        ),
    )
    op.add_column(
        "araclar",
        sa.Column(
            "motor_verimliligi",
            sa.Float(),
            server_default=sa.text("0.38"),
            nullable=False,
        ),
    )
    op.add_column(
        "araclar",
        sa.Column(
            "lastik_direnc_katsayisi",
            sa.Float(),
            server_default=sa.text("0.007"),
            nullable=False,
        ),
    )
    op.add_column(
        "araclar",
        sa.Column(
            "maks_yuk_kapasitesi_kg",
            sa.Integer(),
            server_default=sa.text("26000"),
            nullable=False,
        ),
    )
    # lokasyonlar (Elite Metrics)
    op.add_column(
        "lokasyonlar",
        sa.Column(
            "flat_distance_km",
            sa.Float(),
            server_default=sa.text("0.0"),
            nullable=False,
        ),
    )
    op.add_column(
        "lokasyonlar", sa.Column("otoban_mesafe_km", sa.Float(), nullable=True)
    )
    op.add_column(
        "lokasyonlar", sa.Column("sehir_ici_mesafe_km", sa.Float(), nullable=True)
    )
    op.add_column("lokasyonlar", sa.Column("source", sa.String(50), nullable=True))
    op.add_column(
        "lokasyonlar", sa.Column("correction_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "soforler",
        sa.Column(
            "ramp_skoru", sa.Float(), server_default=sa.text("1.0"), nullable=False
        ),
    )
    op.add_column(
        "soforler",
        sa.Column(
            "istikrar_skoru", sa.Float(), server_default=sa.text("1.0"), nullable=False
        ),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_event_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("arac_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("old_status", sa.String(length=50), nullable=True),
        sa.Column("new_status", sa.String(length=50), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["arac_id"], ["araclar.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vehicle_event_log_arac_id"),
        "vehicle_event_log",
        ["arac_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vehicle_event_log_event_type"),
        "vehicle_event_log",
        ["event_type"],
        unique=False,
    )
    op.add_column(
        "araclar",
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.create_index("idx_arac_aktif", "araclar", ["aktif"], unique=False)
    # op.alter_column(
    #     "lokasyonlar",
    #     "is_corrected",
    #     existing_type=sa.BOOLEAN(),
    #     nullable=False,
    #     existing_server_default=sa.text("false"),
    # )
    op.drop_index(op.f("idx_model_versions_arac_id"), table_name="model_versions")
    op.drop_column("model_versions", "feature_schema_hash")
    op.drop_column("model_versions", "physics_version")
    op.drop_column("model_versions", "training_data_hash")
    # op.alter_column(
    #     "seferler",
    #     "is_real",
    #     existing_type=sa.BOOLEAN(),
    #     nullable=False,
    #     existing_server_default=sa.text("false"),
    # )
    # op.drop_index(
    #     op.f("idx_sefer_no"),
    #     table_name="seferler",
    #     postgresql_where="(sefer_no IS NOT NULL)",
    # )
    op.create_index(op.f("ix_seferler_sefer_no"), "seferler", ["sefer_no"], unique=True)
    # op.alter_column(
    #     "soforler",
    #     "ramp_skoru",
    #     existing_type=sa.DOUBLE_PRECISION(precision=53),
    #     nullable=False,
    #     existing_server_default=sa.text("1.0"),
    # )
    # op.alter_column(
    #     "soforler",
    #     "istikrar_skoru",
    #     existing_type=sa.DOUBLE_PRECISION(precision=53),
    #     nullable=False,
    #     existing_server_default=sa.text("1.0"),
    # )

    op.create_index("idx_sofor_aktif", "soforler", ["aktif"], unique=False)
    op.create_index("idx_yakit_aktif", "yakit_alimlari", ["aktif"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_yakit_aktif", table_name="yakit_alimlari")
    op.drop_index("idx_sofor_aktif", table_name="soforler")
    op.alter_column(
        "soforler",
        "istikrar_skoru",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.alter_column(
        "soforler",
        "ramp_skoru",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("1.0"),
    )
    op.drop_index(op.f("ix_seferler_sefer_no"), table_name="seferler")
    op.create_index(
        op.f("idx_sefer_no"),
        "seferler",
        ["sefer_no"],
        unique=True,
        postgresql_where="(sefer_no IS NOT NULL)",
    )
    op.alter_column(
        "seferler",
        "is_real",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.add_column(
        "model_versions",
        sa.Column(
            "training_data_hash",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "model_versions",
        sa.Column(
            "physics_version", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "model_versions",
        sa.Column(
            "feature_schema_hash",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("idx_model_versions_arac_id"), "model_versions", ["arac_id"], unique=False
    )
    op.alter_column(
        "lokasyonlar",
        "is_corrected",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_index("idx_arac_aktif", table_name="araclar")
    op.drop_column("araclar", "updated_at")
    op.drop_index(
        op.f("ix_vehicle_event_log_event_type"), table_name="vehicle_event_log"
    )
    op.drop_index(op.f("ix_vehicle_event_log_arac_id"), table_name="vehicle_event_log")
    op.drop_table("vehicle_event_log")
    # ### end Alembic commands ###
