"""Add coordinate columns to guzergah

Revision ID: a3214dd89c76
Revises: d42e36e0afe0
Create Date: 2026-02-03 00:02:17.853057

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3214dd89c76"
down_revision: Union[str, Sequence[str], None] = "d42e36e0afe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('guzergahlar', sa.Column('cikis_lat', sa.Float(), nullable=True))
    # op.add_column('guzergahlar', sa.Column('cikis_lon', sa.Float(), nullable=True))
    # op.add_column('guzergahlar', sa.Column('varis_lat', sa.Float(), nullable=True))
    # op.add_column('guzergahlar', sa.Column('varis_lon', sa.Float(), nullable=True))
    # op.add_column('guzergahlar', sa.Column('ascent_m', sa.Float(), nullable=True))
    # op.add_column('guzergahlar', sa.Column('descent_m', sa.Float(), nullable=True))
    # op.add_column('guzergahlar', sa.Column('geometry', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guzergahlar", "geometry")
    op.drop_column("guzergahlar", "descent_m")
    op.drop_column("guzergahlar", "ascent_m")
    op.drop_column("guzergahlar", "varis_lon")
    op.drop_column("guzergahlar", "varis_lat")
    op.drop_column("guzergahlar", "cikis_lon")
    op.drop_column("guzergahlar", "cikis_lat")
    # ### end Alembic commands ###
