"""add_route_analysis_to_lokasyon

Revision ID: a58e2561f362
Revises: 73752c1be58c
Create Date: 2026-02-15 12:51:28.709288

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a58e2561f362"
down_revision: Union[str, Sequence[str], None] = "73752c1be58c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lokasyonlar", sa.Column("route_analysis", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lokasyonlar", "route_analysis")
    # ### end Alembic commands ###
