"""add is_deleted and constraints to sefer

Revision ID: c5b2e5e92a68
Revises: 2309c90b0151
Create Date: 2026-03-05 12:50:07.336256

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5b2e5e92a68"
down_revision: Union[str, Sequence[str], None] = "2309c90b0151"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE IF EXISTS seferler "
        "ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE"
    )
    op.create_index(
        op.f("ix_seferler_is_deleted"), "seferler", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_seferler_log_created_at"), "seferler_log", ["created_at"], unique=False
    )
    op.create_check_constraint("check_sefer_net_kg_positive", "seferler", "net_kg >= 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_sefer_net_kg_positive", "seferler", type_="check")
    op.drop_index(op.f("ix_seferler_log_created_at"), table_name="seferler_log")
    op.drop_index(op.f("ix_seferler_is_deleted"), table_name="seferler")
    op.drop_column("seferler", "is_deleted")
    # ### end Alembic commands ###
