"""Initial migration

Revision ID: cba4911a4a05
Revises:
Create Date: 2026-01-11 12:31:12.580263

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cba4911a4a05"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False
    )
    op.create_index(
        op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_table(
        "araclar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plaka", sa.String(length=20), nullable=False),
        sa.Column("marka", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=True),
        sa.Column("yil", sa.Integer(), nullable=True),
        sa.Column("tank_kapasitesi", sa.Integer(), nullable=False),
        sa.Column("hedef_tuketim", sa.Float(), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("notlar", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_araclar_plaka"), "araclar", ["plaka"], unique=True)
    op.create_table(
        "ayarlar",
        sa.Column("anahtar", sa.String(length=100), nullable=False),
        sa.Column("deger", sa.Text(), nullable=True),
        sa.Column("aciklama", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("anahtar"),
    )
    op.create_table(
        "kullanicilar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kullanici_adi", sa.String(length=50), nullable=False),
        sa.Column("sifre_hash", sa.String(length=255), nullable=False),
        sa.Column("ad_soyad", sa.String(length=100), nullable=True),
        sa.Column("rol", sa.String(length=20), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("son_giris", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kullanicilar_kullanici_adi"),
        "kullanicilar",
        ["kullanici_adi"],
        unique=True,
    )
    op.create_table(
        "lokasyonlar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cikis_yeri", sa.String(length=100), nullable=False),
        sa.Column("varis_yeri", sa.String(length=100), nullable=False),
        sa.Column("mesafe_km", sa.Integer(), nullable=False),
        sa.Column("tahmini_sure_saat", sa.Float(), nullable=True),
        sa.Column("zorluk", sa.String(length=20), nullable=False),
        sa.Column("cikis_lat", sa.Float(), nullable=True),
        sa.Column("cikis_lon", sa.Float(), nullable=True),
        sa.Column("varis_lat", sa.Float(), nullable=True),
        sa.Column("varis_lon", sa.Float(), nullable=True),
        sa.Column("api_mesafe_km", sa.Float(), nullable=True),
        sa.Column("api_sure_saat", sa.Float(), nullable=True),
        sa.Column("ascent_m", sa.Float(), nullable=True),
        sa.Column("descent_m", sa.Float(), nullable=True),
        sa.Column("tahmini_yakit_lt", sa.Float(), nullable=True),
        sa.Column("last_api_call", sa.DateTime(), nullable=True),
        sa.Column("notlar", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cikis_yeri", "varis_yeri", name="uq_cikis_varis"),
    )
    op.create_table(
        "soforler",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_soyad", sa.String(length=100), nullable=False),
        sa.Column("telefon", sa.String(length=20), nullable=True),
        sa.Column("ise_baslama", sa.Date(), nullable=True),
        sa.Column("ehliyet_sinifi", sa.String(length=10), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("notlar", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seferler",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tarih", sa.Date(), nullable=False),
        sa.Column("saat", sa.String(length=5), nullable=True),
        sa.Column("arac_id", sa.Integer(), nullable=False),
        sa.Column("sofor_id", sa.Integer(), nullable=False),
        sa.Column("net_kg", sa.Integer(), nullable=False),
        sa.Column("ton", sa.Float(), nullable=False),
        sa.Column("cikis_yeri", sa.String(length=100), nullable=False),
        sa.Column("varis_yeri", sa.String(length=100), nullable=False),
        sa.Column("mesafe_km", sa.Integer(), nullable=False),
        sa.Column("baslangic_km", sa.Integer(), nullable=True),
        sa.Column("bitis_km", sa.Integer(), nullable=True),
        sa.Column("bos_sefer", sa.Boolean(), nullable=False),
        sa.Column("durum", sa.String(length=20), nullable=False),
        sa.Column("periyot_id", sa.Integer(), nullable=True),
        sa.Column("dagitilan_yakit", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("tahmini_tuketim", sa.Float(), nullable=True),
        sa.Column("rota_detay", sa.JSON(), nullable=True),
        sa.Column("tuketim", sa.Float(), nullable=True),
        sa.Column("ascent_m", sa.Float(), nullable=True),
        sa.Column("descent_m", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["arac_id"],
            ["araclar.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sofor_id"],
            ["soforler.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_seferler_arac_id"), "seferler", ["arac_id"], unique=False)
    op.create_index(
        op.f("ix_seferler_periyot_id"), "seferler", ["periyot_id"], unique=False
    )
    op.create_index(
        op.f("ix_seferler_sofor_id"), "seferler", ["sofor_id"], unique=False
    )
    op.create_index(op.f("ix_seferler_tarih"), "seferler", ["tarih"], unique=False)
    op.create_table(
        "yakit_alimlari",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tarih", sa.Date(), nullable=False),
        sa.Column("arac_id", sa.Integer(), nullable=False),
        sa.Column("istasyon", sa.String(length=100), nullable=True),
        sa.Column("fiyat_tl", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("litre", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("toplam_tutar", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("km_sayac", sa.Integer(), nullable=False),
        sa.Column("fis_no", sa.String(length=50), nullable=True),
        sa.Column("depo_durumu", sa.String(length=20), nullable=False),
        sa.Column("durum", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["arac_id"],
            ["araclar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_yakit_alimlari_arac_id"), "yakit_alimlari", ["arac_id"], unique=False
    )
    op.create_index(
        op.f("ix_yakit_alimlari_tarih"), "yakit_alimlari", ["tarih"], unique=False
    )
    op.create_table(
        "yakit_formul",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("arac_id", sa.Integer(), nullable=False),
        sa.Column("katsayilar", sa.JSON(), nullable=False),
        sa.Column("r2_score", sa.Float(), nullable=True),
        sa.Column("sample_count", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["arac_id"],
            ["araclar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("arac_id"),
    )
    op.create_table(
        "yakit_periyotlari",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("arac_id", sa.Integer(), nullable=False),
        sa.Column("alim1_id", sa.Integer(), nullable=False),
        sa.Column("alim2_id", sa.Integer(), nullable=False),
        sa.Column("alim1_tarih", sa.Date(), nullable=True),
        sa.Column("alim1_km", sa.Integer(), nullable=True),
        sa.Column("alim1_litre", sa.Float(), nullable=True),
        sa.Column("alim2_tarih", sa.Date(), nullable=True),
        sa.Column("alim2_km", sa.Integer(), nullable=True),
        sa.Column("ara_mesafe", sa.Integer(), nullable=True),
        sa.Column("toplam_yakit", sa.Float(), nullable=True),
        sa.Column("ort_tuketim", sa.Float(), nullable=True),
        sa.Column("sefer_sayisi", sa.Integer(), nullable=False),
        sa.Column("durum", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["arac_id"],
            ["araclar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "arac_id", "alim1_id", "alim2_id", name="uq_yakit_periyodu"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("yakit_periyotlari")
    op.drop_table("yakit_formul")
    op.drop_index(op.f("ix_yakit_alimlari_tarih"), table_name="yakit_alimlari")
    op.drop_index(op.f("ix_yakit_alimlari_arac_id"), table_name="yakit_alimlari")
    op.drop_table("yakit_alimlari")
    op.drop_index(op.f("ix_seferler_tarih"), table_name="seferler")
    op.drop_index(op.f("ix_seferler_sofor_id"), table_name="seferler")
    op.drop_index(op.f("ix_seferler_periyot_id"), table_name="seferler")
    op.drop_index(op.f("ix_seferler_arac_id"), table_name="seferler")
    op.drop_table("seferler")
    op.drop_table("soforler")
    op.drop_table("lokasyonlar")
    op.drop_index(op.f("ix_kullanicilar_kullanici_adi"), table_name="kullanicilar")
    op.drop_table("kullanicilar")
    op.drop_table("ayarlar")
    op.drop_index(op.f("ix_araclar_plaka"), table_name="araclar")
    op.drop_table("araclar")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_created_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
