"""add_sefer_columns_and_guzergah_table_v2

Revision ID: d42e36e0afe0
Revises: 0a1e4023a1cb
Create Date: 2026-02-01 22:51:44.528770

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d42e36e0afe0"
down_revision: Union[str, Sequence[str], None] = "0a1e4023a1cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("seferler", sa.Column("guzergah_id", sa.Integer(), nullable=True))
    op.add_column(
        "seferler",
        sa.Column(
            "bos_agirlik_kg", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.add_column(
        "seferler",
        sa.Column(
            "dolu_agirlik_kg", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_seferler_guzergah_id"), "seferler", ["guzergah_id"], unique=False
    )
    op.create_foreign_key(
        None, "seferler", "lokasyonlar", ["guzergah_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("seferler", "aktif")
    op.add_column(
        "yakit_alimlari",
        sa.Column(
            "last_fetched",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("yakit_alimlari", "last_fetched")
    op.add_column(
        "seferler",
        sa.Column(
            "aktif",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "seferler", type_="foreignkey")
    op.drop_index(op.f("ix_seferler_guzergah_id"), table_name="seferler")
    op.drop_column("seferler", "dolu_agirlik_kg")
    op.drop_column("seferler", "bos_agirlik_kg")
    op.drop_column("seferler", "guzergah_id")
    # ### end Alembic commands ###
