"""Add seferler audit logs

Revision ID: d4dfd8f6eeea
Revises: 70b160f9c4ff
Create Date: 2026-03-04 09:25:57.471894

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4dfd8f6eeea"
down_revision: Union[str, Sequence[str], None] = "70b160f9c4ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seferler_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sefer_id", sa.Integer(), nullable=False),
        sa.Column("degisen_alan", sa.String(length=50), nullable=True),
        sa.Column("eski_deger", sa.String(), nullable=True),
        sa.Column("yeni_deger", sa.String(), nullable=True),
        sa.Column("degistiren_id", sa.Integer(), nullable=True),
        sa.Column("islem_tipi", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seferler_log_sefer_id"), "seferler_log", ["sefer_id"], unique=False
    )
    op.add_column("seferler", sa.Column("created_by_id", sa.Integer(), nullable=True))
    op.add_column("seferler", sa.Column("updated_by_id", sa.Integer(), nullable=True))
    op.add_column(
        "seferler", sa.Column("iptal_nedeni", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_seferler_created_by_id"), "seferler", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_seferler_updated_by_id"), "seferler", ["updated_by_id"], unique=False
    )
    op.create_foreign_key(
        None, "seferler", "kullanicilar", ["created_by_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "seferler", "kullanicilar", ["updated_by_id"], ["id"], ondelete="SET NULL"
    )

    # Custom triggers for Audit Log
    op.execute("""
    CREATE OR REPLACE FUNCTION log_seferler_changes()
    RETURNS TRIGGER AS $$
    BEGIN
        IF TG_OP = 'INSERT' THEN
            INSERT INTO seferler_log(sefer_id, islem_tipi, degistiren_id, yeni_deger)
            VALUES (NEW.id, 'INSERT', NEW.created_by_id, row_to_json(NEW)::text);
            RETURN NEW;
        ELSIF TG_OP = 'UPDATE' THEN
            INSERT INTO seferler_log(sefer_id, islem_tipi, degistiren_id, eski_deger, yeni_deger)
            VALUES (NEW.id, 'UPDATE', NEW.updated_by_id, row_to_json(OLD)::text, row_to_json(NEW)::text);
            RETURN NEW;
        ELSIF TG_OP = 'DELETE' THEN
            INSERT INTO seferler_log(sefer_id, islem_tipi, eski_deger)
            VALUES (OLD.id, 'DELETE', row_to_json(OLD)::text);
            RETURN OLD;
        END IF;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER trg_seferler_audit
    AFTER INSERT OR UPDATE OR DELETE ON seferler
    FOR EACH ROW EXECUTE FUNCTION log_seferler_changes();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "seferler", type_="foreignkey")
    op.drop_constraint(None, "seferler", type_="foreignkey")
    op.drop_index(op.f("ix_seferler_updated_by_id"), table_name="seferler")
    op.drop_index(op.f("ix_seferler_created_by_id"), table_name="seferler")
    op.drop_column("seferler", "iptal_nedeni")
    op.drop_column("seferler", "updated_by_id")
    op.drop_column("seferler", "created_by_id")
    op.drop_index(op.f("ix_seferler_log_sefer_id"), table_name="seferler_log")

    # Custom drops for Audit Log
    op.execute("DROP TRIGGER IF EXISTS trg_seferler_audit ON seferler;")
    op.execute("DROP FUNCTION IF EXISTS log_seferler_changes();")

    op.drop_table("seferler_log")
    # ### end Alembic commands ###
