"""Add Dorse separation

Revision ID: d90a84ac7510
Revises: a0b1c2d3e4f5
Create Date: 2026-03-01 20:49:44.535473

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d90a84ac7510"
down_revision: Union[str, Sequence[str], None] = "a0b1c2d3e4f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure route_paths table exists on fresh databases (older migrations omitted it)
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS route_paths (
            id SERIAL PRIMARY KEY,
            origin_lat DOUBLE PRECISION NOT NULL,
            origin_lon DOUBLE PRECISION NOT NULL,
            dest_lat DOUBLE PRECISION NOT NULL,
            dest_lon DOUBLE PRECISION NOT NULL,
            distance_km DOUBLE PRECISION NOT NULL,
            duration_min DOUBLE PRECISION NOT NULL,
            ascent_m DOUBLE PRECISION DEFAULT 0.0,
            descent_m DOUBLE PRECISION DEFAULT 0.0,
            flat_distance_km DOUBLE PRECISION DEFAULT 0.0,
            geometry JSON NOT NULL,
            fuel_estimate_cache JSON,
            last_fetched TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_route_coords UNIQUE (origin_lat, origin_lon, dest_lat, dest_lon)
        );
        """
    )

    op.create_table(
        "dorseler",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plaka", sa.String(length=20), nullable=False),
        sa.Column("marka", sa.String(length=50), nullable=True),
        sa.Column("tipi", sa.String(length=50), nullable=False),
        sa.Column("yil", sa.Integer(), nullable=True),
        sa.Column(
            "bos_agirlik_kg",
            sa.Float(),
            server_default=sa.text("6000.0"),
            nullable=False,
        ),
        sa.Column(
            "maks_yuk_kapasitesi_kg",
            sa.Integer(),
            server_default=sa.text("24000"),
            nullable=False,
        ),
        sa.Column("lastik_sayisi", sa.Integer(), nullable=False),
        sa.Column("dorse_lastik_direnc_katsayisi", sa.Float(), nullable=False),
        sa.Column("dorse_hava_direnci", sa.Float(), nullable=False),
        sa.Column("muayene_tarihi", sa.Date(), nullable=True),
        sa.Column("notlar", sa.Text(), nullable=True),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_dorse_aktif", "dorseler", ["aktif"], unique=False)
    op.create_index(op.f("ix_dorseler_plaka"), "dorseler", ["plaka"], unique=True)
    op.execute(
        "ALTER TABLE IF EXISTS anomalies ALTER COLUMN created_at TYPE TIMESTAMPTZ"
    )
    op.add_column("arac_bakimlari", sa.Column("dorse_id", sa.Integer(), nullable=True))
    op.add_column(
        "arac_bakimlari",
        sa.Column(
            "guncelleme_tarihi",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "arac_bakimlari", "arac_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index(
        op.f("ix_arac_bakimlari_dorse_id"), "arac_bakimlari", ["dorse_id"], unique=False
    )
    op.create_foreign_key(
        None, "arac_bakimlari", "dorseler", ["dorse_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("arac_bakimlari", "olusturma_tarihi")
    op.add_column("araclar", sa.Column("muayene_tarihi", sa.Date(), nullable=True))
    op.alter_column(
        "araclar",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "araclar",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bildirim_gecmisi",
        "olusturma_tarihi",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("bildirim_kurallari", "kanallar")
    op.add_column(
        "bildirim_kurallari",
        sa.Column("kanallar", postgresql.ARRAY(sa.String()), nullable=False),
    )
    op.alter_column(
        "guzergah_kalibrasyonlari",
        "olusturma_tarihi",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.execute(
        "ALTER TABLE IF EXISTS guzergah_kalibrasyonlari DROP COLUMN IF EXISTS hedef_path"
    )
    op.alter_column(
        "lokasyonlar",
        "last_api_call",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "route_paths",
        "last_fetched",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column("seferler", sa.Column("dorse_id", sa.Integer(), nullable=True))
    op.alter_column(
        "seferler",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_seferler_dorse_id"), "seferler", ["dorse_id"], unique=False
    )
    op.create_foreign_key(
        None, "seferler", "dorseler", ["dorse_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column(
        "sofor_adaptasyon",
        "risk_kategorisi",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'Düşük'::character varying"),
    )
    op.alter_column(
        "sofor_adaptasyon",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "soforler",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "vehicle_event_log",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "yakit_alimlari",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "yakit_alimlari",
        "last_fetched",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "yakit_alimlari",
        "last_fetched",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "yakit_alimlari",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "vehicle_event_log",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "soforler",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sofor_adaptasyon",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sofor_adaptasyon",
        "risk_kategorisi",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'Düşük'::character varying"),
    )
    op.drop_constraint(None, "seferler", type_="foreignkey")
    op.drop_index(op.f("ix_seferler_dorse_id"), table_name="seferler")
    op.alter_column(
        "seferler",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("seferler", "dorse_id")
    op.alter_column(
        "route_paths",
        "last_fetched",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "lokasyonlar",
        "last_api_call",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.add_column(
        "guzergah_kalibrasyonlari",
        sa.Column("hedef_path", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "guzergah_kalibrasyonlari",
        "olusturma_tarihi",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "bildirim_kurallari",
        "kanallar",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using="kanallar::jsonb",
    )
    op.alter_column(
        "bildirim_gecmisi",
        "olusturma_tarihi",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "araclar",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "araclar",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("araclar", "muayene_tarihi")
    op.add_column(
        "arac_bakimlari",
        sa.Column(
            "olusturma_tarihi",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "arac_bakimlari", type_="foreignkey")
    op.drop_index(op.f("ix_arac_bakimlari_dorse_id"), table_name="arac_bakimlari")
    op.alter_column(
        "arac_bakimlari", "arac_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("arac_bakimlari", "guncelleme_tarihi")
    op.drop_column("arac_bakimlari", "dorse_id")
    op.execute("ALTER TABLE IF EXISTS anomalies ALTER COLUMN created_at TYPE TIMESTAMP")
    op.drop_index(op.f("ix_dorseler_plaka"), table_name="dorseler")
    op.drop_index("idx_dorse_aktif", table_name="dorseler")
    op.drop_table("dorseler")
    # ### end Alembic commands ###
