"""add_sofor_score_constraints_and_soft_delete

Revision ID: dd39e9ba28d7
Revises: d465eee4f53b
Create Date: 2026-03-05 13:12:57.037584

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd39e9ba28d7"
down_revision: Union[str, Sequence[str], None] = "d465eee4f53b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "soforler",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.create_index("idx_sofor_is_deleted", "soforler", ["is_deleted"], unique=False)
    # ### end Alembic commands ###

    # Manual Additions: CHECK constraints
    op.create_check_constraint(
        "chk_sofor_score_range", "soforler", "score >= 0.1 AND score <= 2.0"
    )
    op.create_check_constraint(
        "chk_sofor_manual_score_range",
        "soforler",
        "manual_score >= 0.1 AND manual_score <= 2.0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chk_sofor_score_range", "soforler", type_="check")
    op.drop_constraint("chk_sofor_manual_score_range", "soforler", type_="check")
    op.drop_index("idx_sofor_is_deleted", table_name="soforler")
    op.drop_column("soforler", "is_deleted")
    # ### end Alembic commands ###
