"""017_ml_versions_queue

Revision ID: ef8abc3ede67
Revises: 157d0af5715d
Create Date: 2026-02-28 12:33:14.398940

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef8abc3ede67"
down_revision: Union[str, Sequence[str], None] = "157d0af5715d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "egitim_kuyrugu",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("arac_id", sa.Integer(), nullable=False),
        sa.Column("hedef_versiyon", sa.Integer(), nullable=False),
        sa.Column("durum", sa.String(length=20), nullable=False),
        sa.Column("ilerleme", sa.Float(), nullable=False),
        sa.Column("hata_detay", sa.Text(), nullable=True),
        sa.Column("yeniden_deneme_sayisi", sa.Integer(), nullable=False),
        sa.Column("baslangic_zaman", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bitis_zaman", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "olusturma",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "guncelleme",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tetikleyen_kullanici_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["arac_id"], ["araclar.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tetikleyen_kullanici_id"], ["kullanicilar.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_egitim_kuyrugu_arac_id"), "egitim_kuyrugu", ["arac_id"], unique=False
    )
    op.create_index(
        op.f("ix_egitim_kuyrugu_durum"), "egitim_kuyrugu", ["durum"], unique=False
    )
    # Indexler yoksa hataya düşmemek için IF EXISTS kullan
    op.execute("DROP INDEX IF EXISTS ix_alerts_alert_type")
    op.execute("DROP INDEX IF EXISTS ix_alerts_created_at")
    op.execute("DROP INDEX IF EXISTS ix_alerts_sofor_id")
    op.execute("DROP INDEX IF EXISTS ix_alerts_status")
    op.execute("DROP TABLE IF EXISTS alerts CASCADE")
    op.execute("DROP TABLE IF EXISTS ayarlar CASCADE")
    op.execute("DROP INDEX IF EXISTS idx_audit_zaman")
    op.execute(
        "ALTER TABLE IF EXISTS anomalies ADD COLUMN IF NOT EXISTS rca_summary TEXT"
    )
    op.execute(
        "ALTER TABLE IF EXISTS anomalies ADD COLUMN IF NOT EXISTS suggested_action TEXT"
    )
    op.execute("DROP INDEX IF EXISTS idx_konfig_gecmis_anahtar")
    op.create_index(
        op.f("ix_konfig_gecmis_anahtar"), "konfig_gecmis", ["anahtar"], unique=False
    )
    op.drop_constraint(
        op.f("konfig_gecmis_guncelleyen_id_fkey"), "konfig_gecmis", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "konfig_gecmis", "kullanicilar", ["guncelleyen_id"], ["id"]
    )
    op.execute("DROP INDEX IF EXISTS idx_oturum_kullanici")
    op.alter_column(
        "kullanicilar", "ad_soyad", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "kullanicilar",
        "sifre_hash",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.alter_column(
        "kullanicilar",
        "son_giris",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "kullanicilar",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.execute("DROP INDEX IF EXISTS idx_kullanici_email")
    op.drop_constraint(op.f("uq_kullanici_email"), "kullanicilar", type_="unique")
    op.create_index(
        op.f("ix_kullanicilar_email"), "kullanicilar", ["email"], unique=True
    )
    op.add_column(
        "model_versiyonlar",
        sa.Column("veri_sayisi", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column("model_versiyonlar", sa.Column("notlar", sa.Text(), nullable=True))
    op.alter_column(
        "model_versiyonlar",
        "egitim_tarihi",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.execute("DROP INDEX IF EXISTS ix_model_versions_arac_id")
    op.create_index(
        op.f("ix_model_versiyonlar_arac_id"),
        "model_versiyonlar",
        ["arac_id"],
        unique=False,
    )
    op.drop_column("model_versiyonlar", "notes")
    op.drop_constraint(
        op.f("sistem_konfig_guncelleyen_id_fkey"), "sistem_konfig", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "sistem_konfig", "kullanicilar", ["guncelleyen_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sistem_konfig", type_="foreignkey")
    op.create_foreign_key(
        op.f("sistem_konfig_guncelleyen_id_fkey"),
        "sistem_konfig",
        "kullanicilar",
        ["guncelleyen_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "model_versiyonlar",
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_model_versiyonlar_arac_id"), table_name="model_versiyonlar")
    op.create_index(
        op.f("ix_model_versions_arac_id"),
        "model_versiyonlar",
        ["arac_id"],
        unique=False,
    )
    op.alter_column(
        "model_versiyonlar",
        "egitim_tarihi",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("model_versiyonlar", "notlar")
    op.drop_column("model_versiyonlar", "veri_sayisi")
    op.drop_index(op.f("ix_kullanicilar_email"), table_name="kullanicilar")
    op.create_unique_constraint(
        op.f("uq_kullanici_email"),
        "kullanicilar",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_kullanici_email"), "kullanicilar", ["email"], unique=False
    )
    op.alter_column(
        "kullanicilar",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "kullanicilar",
        "son_giris",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "kullanicilar",
        "sifre_hash",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "kullanicilar", "ad_soyad", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.create_index(
        op.f("idx_oturum_kullanici"),
        "kullanici_oturumlari",
        ["kullanici_id", "aktif"],
        unique=False,
    )
    op.drop_constraint(None, "konfig_gecmis", type_="foreignkey")
    op.create_foreign_key(
        op.f("konfig_gecmis_guncelleyen_id_fkey"),
        "konfig_gecmis",
        "kullanicilar",
        ["guncelleyen_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_konfig_gecmis_anahtar"), table_name="konfig_gecmis")
    op.create_index(
        op.f("idx_konfig_gecmis_anahtar"), "konfig_gecmis", ["anahtar"], unique=False
    )
    op.execute("ALTER TABLE IF EXISTS anomalies DROP COLUMN IF EXISTS suggested_action")
    op.execute("ALTER TABLE IF EXISTS anomalies DROP COLUMN IF EXISTS rca_summary")
    op.create_index(
        op.f("idx_audit_zaman"),
        "admin_audit_log",
        [sa.literal_column("zaman DESC")],
        unique=False,
    )
    op.create_table(
        "ayarlar",
        sa.Column(
            "anahtar", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("deger", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("aciklama", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("anahtar", name=op.f("ayarlar_pkey")),
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "alert_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "severity", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("source_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "source_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("sofor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "read_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["sofor_id"],
            ["soforler.id"],
            name=op.f("alerts_sofor_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("alerts_pkey")),
    )
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(op.f("ix_alerts_sofor_id"), "alerts", ["sofor_id"], unique=False)
    op.create_index(
        op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False
    )
    op.execute("DROP INDEX IF EXISTS ix_egitim_kuyrugu_durum")
    op.execute("DROP INDEX IF EXISTS ix_egitim_kuyrugu_arac_id")
    op.execute("DROP TABLE IF EXISTS egitim_kuyrugu CASCADE")
    # ### end Alembic commands ###
