"""update_sefer_guzergah_fk_to_lokasyonlar

Revision ID: f93d33b10f23
Revises: 5c83e424a0f3
Create Date: 2026-02-03 21:39:22.702975

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f93d33b10f23"
down_revision: Union[str, Sequence[str], None] = "5c83e424a0f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('seferler_guzergah_id_fkey'), 'seferler', type_='foreignkey')
    # op.create_foreign_key(None, 'seferler', 'lokasyonlar', ['guzergah_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "seferler", type_="foreignkey")
    op.create_foreign_key(
        op.f("seferler_guzergah_id_fkey"),
        "seferler",
        "guzergahlar",
        ["guzergah_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
