export const investigationsText = {
  tabLabel: "Soruşturmalar",
  sectionTitle: "Yakıt Hırsızlığı Soruşturmaları",
  emptyKanban: "Henüz soruşturma yok.",
  columnLabels: {
    open: "Açık",
    assigned: "Atandı",
    investigating: "Soruşturuluyor",
    resolved: "Çözüldü",
    closed: "Kapandı",
  },
  suspicionLabels: {
    low: "Düşük",
    medium: "Orta",
    high: "Yüksek",
    unknown: "Belirsiz",
  },
  resolutionLabels: {
    real_theft: "Gerçek hırsızlık",
    false_alarm: "Sahte alarm",
    data_error: "Veri hatası",
    inconclusive: "Belirsiz",
  },
  actions: {
    save: "Kaydet",
    cancel: "İptal",
    close: "Kapat",
    delete: "Soruşturmayı kapat",
    addEvidence: "+ URL ekle",
  },
  fields: {
    status: "Durum",
    suspicion: "Şüphe",
    score: "Skor",
    assigned: "Atanan",
    notes: "Notlar",
    resolution: "Çözüm Tipi",
    evidence: "Kanıt (URL listesi)",
    plaka: "Plaka",
    sofor: "Şoför",
    sapma: "Sapma",
    created: "Oluşturma",
  },
  notRegistered: "— atanmamış —",
  successUpdate: "Soruşturma güncellendi.",
  errorUpdate: "Güncellenemedi.",
  confirmClose: "Bu soruşturmayı kapatmak istediğinize emin misiniz?",
  successClose: "Soruşturma kapatıldı.",
  pattern: {
    title: "Tekrarlayan Örüntüler",
    subtitle: (days: number) => `Son ${days} gün — ≥ N olay`,
    minCountLabel: "Min olay",
    daysLabel: "Pencere (gün)",
    empty: "Tekrarlayan örüntü bulunamadı.",
    columns: {
      sofor: "Şoför",
      plaka: "Plaka",
      count: "Olay",
      avgScore: "Ort. Skor",
      lastSeen: "Son",
    },
  },
} as const;
