export const maintenancePredictionsText = {
  tabs: {
    list: "Liste",
    calendar: "Takvim",
    history: "Geçmiş",
    muayene: "Muayene",
  },
  inspection: {
    vehicles: "Araçlar",
    trailers: "Dorseler",
    overdue: "Muayenesi Geçmiş",
    expiring: "Muayenesi Yaklaşan",
    daysOverdue: (n: number) => `${Math.abs(n)} gün gecikmiş`,
    daysLeft: (n: number) => `${n} gün kaldı`,
    noAlerts: "Muayene uyarısı yok.",
    loadFailed: "Muayene verisi yüklenemedi.",
  },
  breakdown: {
    title: "Arıza Bildir",
    targetLabel: "Tür",
    vehicle: "Araç",
    trailer: "Dorse",
    selectVehicle: "Araç seçiniz…",
    selectTrailer: "Dorse seçiniz…",
    urgencyLabel: "Aciliyet",
    urgent: "Acil",
    fault: "Arıza",
    kmLabel: "KM (opsiyonel)",
    descriptionLabel: "Açıklama",
    descriptionPlaceholder: "Arıza nedir?",
    cancel: "İptal",
    submitting: "Gönderiliyor…",
    submit: "Bildir",
    errVehicleRequired: "Araç seçiniz.",
    errTrailerRequired: "Dorse seçiniz.",
    errGeneric: "Arıza bildirilemedi.",
    successTitle: "Arıza bildirildi",
    successBody: "Açık arıza kaydı oluşturuldu.",
  },
  pageTitle: "Tahmine Dayalı Bakım",
  calendarLegend: {
    overdue: "Gecikmiş",
    soon: "Yakında",
    normal: "Normal",
    low: "Düşük risk",
    unpredictable: "Tahmin yok",
  },
  riskLabels: {
    overdue: "Gecikmiş",
    soon: "Yakında",
    normal: "Normal",
    low: "Düşük",
  } as const,
  table: {
    columns: {
      plaka: "Plaka",
      bakim_tipi: "Bakım Tipi",
      predicted_date: "Tahmini Tarih",
      days_remaining: "Kalan Gün",
      risk_level: "Risk",
      confidence: "Güven",
      savings: "Tasarruf",
      actions: "İşlemler",
    },
    empty: "Henüz tahmin edilebilir bakım yok.",
    unpredictable: "Tahmin için yetersiz veri",
    notApplicable: "—",
    downloadIcs: "Takvime Ekle",
  },
  drawer: {
    title: "Bakım Tahmin Detayı",
    sections: {
      summary: "Özet",
      reasons: "Sebepler",
      actions: "İşlemler",
    },
    labels: {
      plaka: "Plaka",
      bakim_tipi: "Bakım Tipi",
      predicted_date: "Tahmini Tarih",
      days_remaining: "Kalan Gün",
      confidence: "Güven",
      risk: "Risk",
      savings: "Tahmini Tasarruf",
    },
    downloadIcs: "Takvime İndir (.ics)",
    close: "Kapat",
    notPredictable: "Bu araç için yeterli veri yok; tahmin üretilemiyor.",
    downloadError: "Takvim dosyası indirilemedi.",
  },
  errors: {
    loadFailed: "Tahminler yüklenemedi.",
    flagOff: "Bakım tahmin modülü devre dışı.",
    forbidden: "Bu işlem için yetkiniz yok.",
  },
} as const;
