export const routeLabText = {
  heading: "Güzergah Laboratuvarı",
  description:
    "Çıkış-varış girip rotayı 500m segment çözünürlüğünde simüle edin: her parça için hız, eğim ve yakıt tüketimi.",
  form: {
    modeLocation: "Kayıtlı güzergah",
    modeCoords: "Koordinat gir",
    location: "Güzergah",
    locationPlaceholder: "Güzergah seçin",
    vehicle: "Araç (opsiyonel — gerçek teknik specs kullanılır)",
    vehiclePlaceholder: "Varsayılan TIR specs kullan",
    cikisLat: "Çıkış enlem",
    cikisLon: "Çıkış boylam",
    varisLat: "Varış enlem",
    varisLon: "Varış boylam",
    ton: "Yük (ton)",
    aracYasi: "Araç yaşı",
    segmentLength: "Segment boyutu (m)",
    submit: "Simüle Et",
    submitting: "Simüle ediliyor…",
  },
  summary: {
    distance: "Mesafe",
    duration: "Süre",
    totalL: "Toplam yakıt",
    avg: "Ortalama",
    ascent: "Toplam tırmanış",
    descent: "Toplam iniş",
    coverage: "Yükseklik kapsamı",
    km: "km",
    min: "dk",
    liters: "L",
    lper100: "L/100km",
    meters: "m",
  },
  profile: {
    title: "Segment profili",
    subtitle: "Kümülatif mesafe boyunca hız ve tüketim",
    speed: "Hız (km/h)",
    consumption: "Tüketim (L/100km)",
    grade: "Eğim (%)",
    distanceAxis: "Mesafe (km)",
  },
  heatmap: {
    title: "Tüketim haritası",
    subtitle: "Segment rengi = L/100km (yeşil düşük, kırmızı yüksek)",
    legendLow: "< 30",
    legendMid: "30–40",
    legendHigh: "> 40",
    noCoords: "Bu simülasyonda segment koordinatı yok.",
  },
  errors: {
    coordsRequired: "Koordinat modunda çıkış ve varış enlem/boylam zorunludur.",
    rateLimited: "Çok fazla istek. Lütfen biraz bekleyip tekrar deneyin.",
    providerDown: "Rota sağlayıcısı (Mapbox) şu an erişilemez. Tekrar deneyin.",
    generic: "Simülasyon başarısız oldu. Tekrar deneyin.",
  },
  empty: "Bir güzergah seçip 'Simüle Et' deyin.",
  coverageWarning:
    "Yükseklik verisi kısmi — eğim ve tüketim tahmini yaklaşık olabilir.",
} as const;
