export const dataTransferText = {
  toolbarButton: "Excel İşlemleri",
  uploadActionTitle: "Excel'den Yükle",
  uploadActionDescription: "İçe aktarma modülü",
  templateActionTitle: "Örnek Şablon",
  templateActionDescription: "Şablon indir",
  exportActionTitle: "Dışa Aktar",
  exportActionDescription: "Tüm kayıtları Excel'e aktar",
  uploadModal: {
    title: "Excel Kayıtlarını İçe Aktar",
    description:
      "Dosyanızı buraya sürükleyin veya seçmek için tıklayın (.xlsx, .xls)",
    invalidFileType: "Lütfen sadece Excel (.xlsx, .xls) dosyası yükleyin.",
    invalidFileError: "Geçersiz dosya formatı.",
    processing: "Dosya işleniyor...",
    success: "Dosya başarıyla yüklendi!",
    changeFile: "Dosyayı Değiştir",
    idle: "Yüklemek için tıklayın veya sürükleyin",
    allowedFormats: "İzin verilen dosya türleri: .xlsx, .xls",
    uploadErrorFallback: "Yükleme sırasında bir hata oluştu.",
    uploadErrorDetected: "Dosya yüklenirken bazı hatalar tespit edildi.",
    row: "Satır",
    field: "Alan",
    errorReason: "Hata Nedeni",
    processed: "İşlenen",
    saved: "Başarılı",
    failed: "Hatalı",
    cancel: "İptal",
    startUpload: "Yüklemeyi Başlat",
  },
} as const;
