"""Typed service contracts (Protocol ABCs).

These interfaces define the public API contract for each service.
Endpoints and other services depend on these protocols, not concrete classes,
enabling easy mocking and future implementation swaps.
"""

from datetime import date
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class ITripService(Protocol):
    async def get_sefer_by_id(
        self, sefer_id: int, current_user: Any = None
    ) -> Optional[Dict]: ...
    async def get_all_paged(self, **kwargs) -> Dict[str, Any]: ...
    async def create_sefer(self, data: Any) -> int: ...
    async def update_sefer(self, sefer_id: int, data: Any) -> bool: ...
    async def delete_sefer(self, sefer_id: int) -> bool: ...
    async def set_onay_durumu(
        self,
        sefer_id: int,
        yeni_durum: str,
        onay_notu: Optional[str] = None,
        onaylayan_id: Optional[int] = None,
    ) -> Optional[Dict]: ...
    async def get_by_onay_durumu(
        self, onay_durumu: str, skip: int = 0, limit: int = 50
    ) -> List[Dict]: ...


@runtime_checkable
class IDriverService(Protocol):
    async def get_sofor_by_id(self, sofor_id: int) -> Optional[Dict]: ...
    async def get_all_paged(self, **kwargs) -> Dict[str, Any]: ...
    async def add_sofor(self, data: Any) -> int: ...
    async def update_sofor(self, sofor_id: int, data: Any) -> bool: ...
    async def delete_sofor(self, sofor_id: int) -> bool: ...


@runtime_checkable
class IVehicleService(Protocol):
    async def get_arac_by_id(self, arac_id: int) -> Optional[Dict]: ...
    async def get_all_paged(self, **kwargs) -> Dict[str, Any]: ...
    async def add_arac(self, data: Any) -> int: ...
    async def update_arac(self, arac_id: int, data: Any) -> bool: ...
    async def delete_arac(self, arac_id: int) -> bool: ...


@runtime_checkable
class IFuelService(Protocol):
    async def get_yakit_by_id(self, yakit_id: int) -> Optional[Dict]: ...
    async def get_all_paged(self, **kwargs) -> Dict[str, Any]: ...
    async def add_yakit(self, data: Any) -> int: ...
    async def get_stats(self, **kwargs) -> Dict[str, Any]: ...


@runtime_checkable
class IInternalService(Protocol):
    async def get_sofor_by_telegram_id(self, telegram_id: str) -> Optional[Dict]: ...
    async def kaydet_belge(
        self,
        telegram_id: str,
        belge_tipi: str,
        image_bytes: bytes,
        content_type: str,
        telegram_mesaj_id: Optional[int] = None,
    ) -> Dict: ...
    async def get_seferler(
        self, telegram_id: str, limit: int = 10
    ) -> Optional[List[Dict]]: ...
    async def get_sofor_id(self, telegram_id: str) -> Optional[int]: ...
    async def olustur_pdf(
        self, telegram_id: str, baslangic: date, bitis: date
    ) -> Optional[bytes]: ...
